PORTNAME=	acpi_intel_sst-kmod
DISTVERSION=	0.64.0
CATEGORIES=	audio
MASTER_SITES=	GH

MAINTAINER=	spagu@example.com
COMMENT=	Intel Smart Sound Technology Audio Driver for FreeBSD
WWW=		https://github.com/spagu/acpi_intel_sst

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		kmod uidfix

USE_GITHUB=	yes
GH_ACCOUNT=	spagu
GH_PROJECT=	acpi_intel_sst

.include <bsd.port.mk>
